name: Build Typst PDFs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install a Typst CLI binary
      - name: Install Typst
        run: |
          set -eux
          arch="$(uname -m)"
          # grab latest linux-gnu binary for this CPU
          url="$(curl -s https://api.github.com/repos/typst/typst/releases/latest \
                 | grep browser_download_url \
                 | grep linux-gnu \
                 | grep -i "$arch" \
                 | cut -d '"' -f 4)"
          curl -L "$url" -o typst.tar.xz
          mkdir t && tar -xJf typst.tar.xz -C t --strip-components=1
          sudo mv t/typst /usr/local/bin/typst
          typst --version

      # Build every notes/**/*.typ to pdf/**/<same tree>.pdf
      - name: Compile PDFs into pdf/
        run: |
          set -eux
          shopt -s globstar nullglob
          for f in notes/**/*.typ; do
            rel="${f#notes/}"
            out="pdf/${rel%.typ}.pdf"
            mkdir -p "$(dirname "$out")"
            typst compile --root . "$f" "$out"
          done

      # Save the PDFs on the run for easy download
      - name: Upload PDFs artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: pdf/**
