name: Build Typst PDFs
on:
  push:
    paths:
      - "notes/**/*.typ"
      - "templates/note.typ"
      - "preamble.typ"
      - "typst.toml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Typst
        run: |
          curl -L https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-gnu.tar.xz -o typst.tar.xz
          mkdir typst-bin
          tar -xf typst.tar.xz -C typst-bin --strip-components=1
          echo "$PWD/typst-bin" >> $GITHUB_PATH

      - name: Compile all notes to pdf/
        shell: bash
        run: |
          mkdir -p pdf
          while IFS= read -r -d '' f; do
            rel="${f#notes/}"
            dir="$(dirname "$rel")"
            mkdir -p "pdf/$dir"
            typst compile "$f" "pdf/${rel%.typ}.pdf"
          done < <(find notes -name '*.typ' -print0)

      - name: Commit PDFs back to main
        if: github.ref_name == 'main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pdf
          if git diff --cached --quiet; then
            echo "No PDF changes."
          else
            git commit -m "CI: build PDFs"
            git push
          fi

      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: pdf
